/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import javax.swing.JPanel;

/**
 *
 * @author Debor
 */
public class GerenciamentoModalidade extends javax.swing.JFrame {

    /**
     * Creates new form GerenciamentoModalidade
     */
    public GerenciamentoModalidade() {
        initComponents();
    }

//    public class jPanelGradient extends JPanel{
//        @Override
//        protected void paintComponent(Graphics g){
//            Graphics2D g2d = (Graphics2D) g;
//            int width = getWidth();
//            int height = getHeight();
//            
//            Color color1 = new Color(27,25,30);
//            Color color2 = new Color(124, 124, 124);
//            GradientPaint gp = new GradientPaint(0,0,color1,180,height, color2);
//            g2d.setPaint(gp);
//            g2d.fillRect(0,0,width,height);
//        }
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCRUDModalidade = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldValorModalidade = new javax.swing.JTextField();
        jTextFieldNomeModalidade = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonCancelarModalidade = new javax.swing.JButton();
        jButtonSalvarModalidade = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelCRUDModalidade.setBackground(new java.awt.Color(27, 25, 30));
        jPanelCRUDModalidade.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cadastrar Modalidades");
        jPanelCRUDModalidade.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, -1, -1));

        jTextFieldValorModalidade.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextFieldValorModalidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldValorModalidadeActionPerformed(evt);
            }
        });
        jPanelCRUDModalidade.add(jTextFieldValorModalidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 330, 290, 30));

        jTextFieldNomeModalidade.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanelCRUDModalidade.add(jTextFieldNomeModalidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 220, 290, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI Symbol", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nome");
        jPanelCRUDModalidade.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 190, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Symbol", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Valor");
        jPanelCRUDModalidade.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 300, -1, -1));

        jButtonCancelarModalidade.setBackground(new java.awt.Color(255, 51, 51));
        jButtonCancelarModalidade.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jButtonCancelarModalidade.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCancelarModalidade.setText("Cancelar");
        jButtonCancelarModalidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarModalidadeActionPerformed(evt);
            }
        });
        jPanelCRUDModalidade.add(jButtonCancelarModalidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 430, 100, 30));

        jButtonSalvarModalidade.setBackground(new java.awt.Color(84, 182, 19));
        jButtonSalvarModalidade.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jButtonSalvarModalidade.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalvarModalidade.setText("Salvar");
        jButtonSalvarModalidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarModalidadeActionPerformed(evt);
            }
        });
        jPanelCRUDModalidade.add(jButtonSalvarModalidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 430, 100, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesosPretos2.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanelCRUDModalidade.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 600));
        jPanelCRUDModalidade.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 122, 480, 30));

        getContentPane().add(jPanelCRUDModalidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarModalidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarModalidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCancelarModalidadeActionPerformed

    private void jButtonSalvarModalidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarModalidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSalvarModalidadeActionPerformed

    private void jTextFieldValorModalidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldValorModalidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldValorModalidadeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciamentoModalidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciamentoModalidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciamentoModalidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciamentoModalidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenciamentoModalidade().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelarModalidade;
    private javax.swing.JButton jButtonSalvarModalidade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanelCRUDModalidade;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldNomeModalidade;
    private javax.swing.JTextField jTextFieldValorModalidade;
    // End of variables declaration//GEN-END:variables
}
