/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

/**
 *
 * @author Debor
 */
public class GerenciamentoModalidadeEditar extends javax.swing.JFrame {

    /**
     * Creates new form GerenciamentoModalidadeEditar
     */
    public GerenciamentoModalidadeEditar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelCRUDModalidade = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jTextFieldValorModalidadeEdit = new javax.swing.JTextField();
        jTextFieldNomeModalidadeEdit = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonCancelarModalidadeEdit = new javax.swing.JButton();
        jButtonSalvarModalidadeEdit = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(27, 25, 30));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelCRUDModalidade.setBackground(new java.awt.Color(27, 25, 30));
        jPanelCRUDModalidade.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Editar Modalidades");
        jPanelCRUDModalidade.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 50, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanelCRUDModalidade.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, 480, 30));

        jTextFieldValorModalidadeEdit.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextFieldValorModalidadeEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldValorModalidadeEditActionPerformed(evt);
            }
        });
        jPanelCRUDModalidade.add(jTextFieldValorModalidadeEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 340, 290, 30));

        jTextFieldNomeModalidadeEdit.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanelCRUDModalidade.add(jTextFieldNomeModalidadeEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 230, 290, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI Symbol", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nome");
        jPanelCRUDModalidade.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 200, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Symbol", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Valor");
        jPanelCRUDModalidade.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 310, -1, -1));

        jButtonCancelarModalidadeEdit.setBackground(new java.awt.Color(255, 51, 51));
        jButtonCancelarModalidadeEdit.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jButtonCancelarModalidadeEdit.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCancelarModalidadeEdit.setText("Cancelar");
        jButtonCancelarModalidadeEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarModalidadeEditActionPerformed(evt);
            }
        });
        jPanelCRUDModalidade.add(jButtonCancelarModalidadeEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 450, 100, 30));

        jButtonSalvarModalidadeEdit.setBackground(new java.awt.Color(84, 182, 19));
        jButtonSalvarModalidadeEdit.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jButtonSalvarModalidadeEdit.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalvarModalidadeEdit.setText("Salvar");
        jButtonSalvarModalidadeEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarModalidadeEditActionPerformed(evt);
            }
        });
        jPanelCRUDModalidade.add(jButtonSalvarModalidadeEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 450, 100, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesosPretos2.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanelCRUDModalidade.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 600));

        jPanel1.add(jPanelCRUDModalidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldValorModalidadeEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldValorModalidadeEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldValorModalidadeEditActionPerformed

    private void jButtonCancelarModalidadeEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarModalidadeEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCancelarModalidadeEditActionPerformed

    private void jButtonSalvarModalidadeEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarModalidadeEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSalvarModalidadeEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciamentoModalidadeEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciamentoModalidadeEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciamentoModalidadeEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciamentoModalidadeEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenciamentoModalidadeEditar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelarModalidadeEdit;
    private javax.swing.JButton jButtonSalvarModalidadeEdit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelCRUDModalidade;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldNomeModalidadeEdit;
    private javax.swing.JTextField jTextFieldValorModalidadeEdit;
    // End of variables declaration//GEN-END:variables
}
