/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Controllers.GerenciadorPacotesController;
import Models.Pacote;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Debor
 */
public class GerenciamentoPacote extends javax.swing.JFrame {

    Pacote pacote;
    Pacote editarPacote;
    GerenciadorPacotesController pacoteController = new GerenciadorPacotesController();
    List<Pacote> listaDePacotes;
    DefaultListModel listaDeItensJlist = new DefaultListModel();
    double valor = 0.0;

    /**
     * Creates new form GerenciamentoPacote
     */
    public GerenciamentoPacote() {
        initComponents();
    }

    GerenciamentoPacote(Pacote pacote) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        tituloTelaCRUDMod = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        nomePacote = new javax.swing.JTextField();
        duracaoPacote = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButtonCancelarPacote = new javax.swing.JButton();
        jButtonSalvarPacote = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxModalidades = new javax.swing.JComboBox<>();
        modalidadesPacote = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        valorPacote = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(27, 25, 30));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tituloTelaCRUDMod.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        tituloTelaCRUDMod.setForeground(new java.awt.Color(255, 255, 255));
        tituloTelaCRUDMod.setText("Cadastrar Pacote");
        jPanel2.add(tituloTelaCRUDMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 510, 10));

        jLabel2.setFont(new java.awt.Font("Segoe UI Symbol", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nome");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, -1, -1));

        nomePacote.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        nomePacote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomePacoteActionPerformed(evt);
            }
        });
        jPanel2.add(nomePacote, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 290, 30));

        duracaoPacote.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        duracaoPacote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duracaoPacoteActionPerformed(evt);
            }
        });
        jPanel2.add(duracaoPacote, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 120, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI Symbol", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Modalidades");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jButtonCancelarPacote.setBackground(new java.awt.Color(255, 51, 51));
        jButtonCancelarPacote.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jButtonCancelarPacote.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCancelarPacote.setText("Cancelar");
        jButtonCancelarPacote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarPacoteActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonCancelarPacote, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 100, 30));

        jButtonSalvarPacote.setBackground(new java.awt.Color(84, 182, 19));
        jButtonSalvarPacote.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jButtonSalvarPacote.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalvarPacote.setText("Salvar");
        jButtonSalvarPacote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarPacoteActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonSalvarPacote, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 100, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI Symbol", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Duração");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, -1, -1));

        jComboBoxModalidades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(jComboBoxModalidades, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, -1, -1));

        modalidadesPacote.setText("jTextField1");
        jPanel2.add(modalidadesPacote, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 200, 80));

        jLabel5.setFont(new java.awt.Font("Segoe UI Symbol", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Valor");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, -1, -1));

        valorPacote.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        valorPacote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorPacoteActionPerformed(evt);
            }
        });
        jPanel2.add(valorPacote, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 120, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 490, 440));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesosPretos1000.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 590));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nomePacoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomePacoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomePacoteActionPerformed

    private void duracaoPacoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duracaoPacoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_duracaoPacoteActionPerformed

    private void jButtonCancelarPacoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarPacoteActionPerformed

        int resposta = JOptionPane.showConfirmDialog(rootPane,
            "Tem certeza que deseja cancelar? ",
            "Selecione uma Opção",
            JOptionPane.YES_NO_OPTION);

        if (resposta != 1 & resposta != 2 & resposta != -1) {
            MenuPacote menuPacote = new MenuPacote();
            menuPacote.setVisible(true);
            dispose();

        }
    }//GEN-LAST:event_jButtonCancelarPacoteActionPerformed

    private void jButtonSalvarPacoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarPacoteActionPerformed
        
    }//GEN-LAST:event_jButtonSalvarPacoteActionPerformed

    private void valorPacoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorPacoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorPacoteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciamentoPacote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciamentoPacote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciamentoPacote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciamentoPacote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenciamentoPacote().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField duracaoPacote;
    private javax.swing.JButton jButtonCancelarPacote;
    private javax.swing.JButton jButtonSalvarPacote;
    private javax.swing.JComboBox<String> jComboBoxModalidades;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField modalidadesPacote;
    private javax.swing.JTextField nomePacote;
    private javax.swing.JLabel tituloTelaCRUDMod;
    private javax.swing.JTextField valorPacote;
    // End of variables declaration//GEN-END:variables
}
