/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Controllers.GerenciamentoAlunosController;
import Models.Aluno;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author mathe
 */
public class GerenciamentoFrequencia extends javax.swing.JFrame {

    List<Aluno> listaDeAlunos;
    GerenciamentoAlunosController gerenciamentoDeAlunos = new GerenciamentoAlunosController();
    DefaultListModel listaDeItensJlist = new DefaultListModel();

    /**
     * Creates new form GerenciamentoFrequencia
     */
    public GerenciamentoFrequencia() {
        initComponents();
        popularListaDeAlunos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        campoPesquisaAluno = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        opcaoPresenta = new javax.swing.JRadioButton();
        opcaoAusente = new javax.swing.JRadioButton();
        lancarFrequencia = new javax.swing.JButton();
        buscarAluno = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        alunosResultado = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(95, 158, 160));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(11, 133, 176));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/back2.png"))); // NOI18N
        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        campoPesquisaAluno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        campoPesquisaAluno.setToolTipText("");
        jPanel1.add(campoPesquisaAluno, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 250, 32));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pesquisa o Aluno Desejado:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, -1, -1));

        buttonGroup1.add(opcaoPresenta);
        opcaoPresenta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        opcaoPresenta.setForeground(new java.awt.Color(255, 255, 255));
        opcaoPresenta.setText("Presente");
        jPanel1.add(opcaoPresenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, -1, -1));

        buttonGroup1.add(opcaoAusente);
        opcaoAusente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        opcaoAusente.setForeground(new java.awt.Color(255, 255, 255));
        opcaoAusente.setText("Ausente");
        jPanel1.add(opcaoAusente, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, -1, -1));

        lancarFrequencia.setBackground(new java.awt.Color(0, 204, 0));
        lancarFrequencia.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lancarFrequencia.setForeground(new java.awt.Color(255, 255, 255));
        lancarFrequencia.setText("Lançar Frequência");
        lancarFrequencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lancarFrequenciaActionPerformed(evt);
            }
        });
        jPanel1.add(lancarFrequencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, 190, 40));

        buscarAluno.setBackground(new java.awt.Color(95, 158, 160));
        buscarAluno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buscarAluno.setForeground(new java.awt.Color(255, 255, 255));
        buscarAluno.setText("Buscar");
        buscarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarAlunoActionPerformed(evt);
            }
        });
        jPanel1.add(buscarAluno, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, 90, 30));

        alunosResultado.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jScrollPane1.setViewportView(alunosResultado);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 370, 100));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Resultado:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 90, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 490));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        QuadroPrincipal quadroPrincipal = new QuadroPrincipal();
        quadroPrincipal.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void lancarFrequenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lancarFrequenciaActionPerformed

    }//GEN-LAST:event_lancarFrequenciaActionPerformed

    private void buscarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarAlunoActionPerformed
        if (buscarAluno(campoPesquisaAluno.getText()).size() > 0) {
            preencherLista(buscarAluno(campoPesquisaAluno.getText()));
        } else {
            JOptionPane.showMessageDialog(this, "Ops!! Nenhum Aluno foi encontrado.");
        }
    }//GEN-LAST:event_buscarAlunoActionPerformed

    private void preencherLista(List<Aluno> alunos) {
        for (int i = 0; i < alunos.size(); i++) {
            listaDeItensJlist.addElement(alunos.get(i).getNome() + ", " + alunos.get(i).getCpf());
        }
        alunosResultado.setModel(listaDeItensJlist);
    }

    private List<Aluno> buscarAluno(String valorDigitado) {
        ArrayList<Aluno> resultado = new ArrayList<>();
        for (int i = 0; i < listaDeAlunos.size(); i++) {
            if (valorDigitado.equalsIgnoreCase(listaDeAlunos.get(i).getNome()) || listaDeAlunos.get(i).getNome().contains(valorDigitado)) {
                resultado.add(listaDeAlunos.get(i));
            }
        }
        return resultado;
    }

    private void popularListaDeAlunos() {
        try {
            listaDeAlunos = gerenciamentoDeAlunos.getListaDeAlunos();
        } catch (ParseException ex) {
            Logger.getLogger(GerenciamentoFrequencia.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciamentoFrequencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciamentoFrequencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciamentoFrequencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciamentoFrequencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenciamentoFrequencia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> alunosResultado;
    private javax.swing.JButton buscarAluno;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField campoPesquisaAluno;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton lancarFrequencia;
    private javax.swing.JRadioButton opcaoAusente;
    private javax.swing.JRadioButton opcaoPresenta;
    // End of variables declaration//GEN-END:variables
}
