/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Controllers.GerenciamentoAlunosController;
import Models.Aluno;
import java.text.ParseException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author mathe
 */
public class VisualizarFrequencia extends javax.swing.JFrame {

    DefaultTableModel dtm;
    List<Aluno> listaDeAlunos;
    GerenciamentoAlunosController controllerAluno = new GerenciamentoAlunosController();

    /**
     * Creates new form VisualizarFrequencia
     */
    public VisualizarFrequencia() {
        initComponents();
        popularTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaDeFrequenciaAlunos = new javax.swing.JTable();
        voltarButton = new javax.swing.JButton();
        campoInputFiltro = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(95, 158, 160));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelaDeFrequenciaAlunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Telefone Principal", "Telefone Secundário", "Ultima Frequência"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaDeFrequenciaAlunos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 990, 290));

        voltarButton.setBackground(new java.awt.Color(11, 133, 176));
        voltarButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        voltarButton.setForeground(new java.awt.Color(255, 255, 255));
        voltarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/back2.png"))); // NOI18N
        voltarButton.setText("Voltar");
        voltarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButtonActionPerformed(evt);
            }
        });
        jPanel1.add(voltarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        campoInputFiltro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        campoInputFiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoInputFiltroKeyReleased(evt);
            }
        });
        jPanel1.add(campoInputFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 280, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pesquise:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 100, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Frequência dos Alunos");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 149, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Lançar Frequência");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 20, 160, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButtonActionPerformed
        QuadroPrincipal quadroPrincipal = new QuadroPrincipal();
        quadroPrincipal.setVisible(true);
        dispose();
    }//GEN-LAST:event_voltarButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void campoInputFiltroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoInputFiltroKeyReleased
        String texto = campoInputFiltro.getText();
        filtrar(texto);
    }//GEN-LAST:event_campoInputFiltroKeyReleased

    private void popularTabela() {
        dtm = (DefaultTableModel) tabelaDeFrequenciaAlunos.getModel();
        dtm.setNumRows(0);
        int tamanhoDaLista = 0;
        String textoColunaFrequencia = "";
        try {
            listaDeAlunos = controllerAluno.getListaDeAlunos();
            if (listaDeAlunos.size() > 0) {
                for (int i = 0; i < listaDeAlunos.size(); i++) {
                    tamanhoDaLista = listaDeAlunos.get(i).getFrequencias().size();
                    if (tamanhoDaLista == 0) {
                        textoColunaFrequencia = "Nenhuma frequência cadastrada";
                    } else {
                        textoColunaFrequencia = controllerAluno.verificarFrequenciaAluno(listaDeAlunos.
                                get(i).getFrequencias().get(listaDeAlunos.get(i).
                                getFrequencias().size() - 1));
                    }
                    dtm.addRow(new Object[]{
                        listaDeAlunos.get(i).getNome(),
                        listaDeAlunos.get(i).getTelefonePrincipal(),
                        listaDeAlunos.get(i).getTelefoneSecundario(),
                        textoColunaFrequencia
                    });
                }
            }
        } catch (ParseException ex) {
            Logger.getLogger(VisualizarFrequencia.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void filtrar(String valor) {
        try {
            TableRowSorter<DefaultTableModel> resultadoFiltro = new TableRowSorter<>(dtm);
            tabelaDeFrequenciaAlunos.setRowSorter(resultadoFiltro);
            resultadoFiltro.setRowFilter(RowFilter.regexFilter(valor));
        } catch (Exception e) {
            System.out.println("Caractere não aceito.");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisualizarFrequencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new VisualizarFrequencia().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoInputFiltro;
    private javax.swing.JTextField campoValorFiltro;
    private javax.swing.JTextField campoValorFiltro1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaDeFrequenciaAlunos;
    private javax.swing.JButton voltarButton;
    // End of variables declaration//GEN-END:variables
}
