/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.ModuloPacote;

import Views.ModuloAluno.MenuAlunos;
import Controllers.GerenciadorPacotesController;
import Models.Pacote;
import Views.MenuInicial;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Debor
 */
public class MenuPacote extends javax.swing.JFrame {

    List<Pacote> listaDePacotes;
    int indiceSelecionado;
    GerenciadorPacotesController controllerPacotes = new GerenciadorPacotesController();
    DefaultTableModel dtm;

    /**
     * Creates new form MenuPacote
     */
    public MenuPacote() {
        initComponents();
        try {
            popularTabelaPacote();
        } catch (ParseException ex) {
            Logger.getLogger(MenuPacote.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaPacotes = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        pacoteFiltro = new javax.swing.JTextField();
        editarPacote = new javax.swing.JButton();
        excluirPacote = new javax.swing.JButton();
        cadastrarPacote = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        gerenciarAlunosButton = new javax.swing.JButton();
        jButtonGerenciarPacotes = new javax.swing.JButton();
        jButtonGerenciarModalidades = new javax.swing.JButton();
        jButtonGerenciarCustos = new javax.swing.JButton();
        jButtonInicial = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelaPacotes.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        tabelaPacotes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome", "Valor (Com desconto)", "Duração (Em Meses)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaPacotes);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 550, 330));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/procurar.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, -1, -1));

        pacoteFiltro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pacoteFiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pacoteFiltroKeyReleased(evt);
            }
        });
        jPanel1.add(pacoteFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 210, -1));

        editarPacote.setBackground(new java.awt.Color(0, 153, 255));
        editarPacote.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        editarPacote.setForeground(new java.awt.Color(255, 255, 255));
        editarPacote.setText("Editar");
        editarPacote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarPacoteActionPerformed(evt);
            }
        });
        jPanel1.add(editarPacote, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 140, -1, -1));

        excluirPacote.setBackground(new java.awt.Color(255, 0, 0));
        excluirPacote.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        excluirPacote.setForeground(new java.awt.Color(255, 255, 255));
        excluirPacote.setText("Excluir");
        excluirPacote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirPacoteActionPerformed(evt);
            }
        });
        jPanel1.add(excluirPacote, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 140, -1, -1));

        cadastrarPacote.setBackground(new java.awt.Color(0, 149, 0));
        cadastrarPacote.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        cadastrarPacote.setForeground(new java.awt.Color(255, 255, 255));
        cadastrarPacote.setText("Cadastrar");
        cadastrarPacote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarPacoteActionPerformed(evt);
            }
        });
        jPanel1.add(cadastrarPacote, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 520, 110, 30));

        jPanel2.setBackground(new java.awt.Color(27, 25, 30));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gerenciarAlunosButton.setBackground(new java.awt.Color(102, 102, 102));
        gerenciarAlunosButton.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        gerenciarAlunosButton.setForeground(new java.awt.Color(255, 255, 255));
        gerenciarAlunosButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/mulher (1).png"))); // NOI18N
        gerenciarAlunosButton.setText("Gerenciar Alunos");
        gerenciarAlunosButton.setToolTipText("");
        gerenciarAlunosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerenciarAlunosButtonActionPerformed(evt);
            }
        });
        jPanel2.add(gerenciarAlunosButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 250, 30));

        jButtonGerenciarPacotes.setBackground(new java.awt.Color(102, 102, 102));
        jButtonGerenciarPacotes.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jButtonGerenciarPacotes.setForeground(new java.awt.Color(255, 255, 255));
        jButtonGerenciarPacotes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/caixa.png"))); // NOI18N
        jButtonGerenciarPacotes.setText("Gerenciar Pacotes");
        jButtonGerenciarPacotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGerenciarPacotesActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonGerenciarPacotes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 250, -1));

        jButtonGerenciarModalidades.setBackground(new java.awt.Color(102, 102, 102));
        jButtonGerenciarModalidades.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jButtonGerenciarModalidades.setForeground(new java.awt.Color(255, 255, 255));
        jButtonGerenciarModalidades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/academia.png"))); // NOI18N
        jButtonGerenciarModalidades.setText("Gerenciar Modalidades");
        jButtonGerenciarModalidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGerenciarModalidadesActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonGerenciarModalidades, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 250, -1));

        jButtonGerenciarCustos.setBackground(new java.awt.Color(102, 102, 102));
        jButtonGerenciarCustos.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jButtonGerenciarCustos.setForeground(new java.awt.Color(255, 255, 255));
        jButtonGerenciarCustos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/dinheiro.png"))); // NOI18N
        jButtonGerenciarCustos.setText("Gerenciar Custos");
        jPanel2.add(jButtonGerenciarCustos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 250, -1));

        jButtonInicial.setBackground(new java.awt.Color(102, 102, 102));
        jButtonInicial.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jButtonInicial.setForeground(new java.awt.Color(255, 255, 255));
        jButtonInicial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/casa (1).png"))); // NOI18N
        jButtonInicial.setText("Inicio");
        jButtonInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInicialActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 250, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vidafitnes-removebg-preview (1).png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 600));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagemTenisCerta.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 730, 600));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void gerenciarAlunosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerenciarAlunosButtonActionPerformed
        MenuAlunos menuAlunos = new MenuAlunos();
        menuAlunos.setVisible(true);
        dispose();
    }//GEN-LAST:event_gerenciarAlunosButtonActionPerformed

    private void jButtonGerenciarPacotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGerenciarPacotesActionPerformed
        MenuPacote menuPacote = new MenuPacote();
        menuPacote.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonGerenciarPacotesActionPerformed

    private void pacoteFiltroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pacoteFiltroKeyReleased
        String nome = pacoteFiltro.getText();
        filtrar(nome);
    }//GEN-LAST:event_pacoteFiltroKeyReleased

    private void editarPacoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarPacoteActionPerformed
        if (tabelaPacotes.getSelectedRow() >= 0) {
            int linhaSelecionada = tabelaPacotes.getSelectedRow();
            String nome;
            nome = (String) tabelaPacotes.getValueAt(linhaSelecionada, 0);
            CadastroEdicaoPacote edicaoCadastroPacote = new CadastroEdicaoPacote(buscarPacoteNaLista(nome));
            edicaoCadastroPacote.setVisible(true);
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Nenhum pacote foi selecionado!");
        }

    }//GEN-LAST:event_editarPacoteActionPerformed

    private Pacote buscarPacoteNaLista(String nome) {
        for (int i = 0; i < listaDePacotes.size(); i++) {
            if (nome.equalsIgnoreCase(listaDePacotes.get(i).getNomePacote())) {
                return listaDePacotes.get(i);
            }
        }
        return null;
    }

    private void excluirPacoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirPacoteActionPerformed
        if (tabelaPacotes.getSelectedRow() >= 0) {
            int linhaSelecionada = tabelaPacotes.getSelectedRow();
            String nome;
            nome = (String) tabelaPacotes.getValueAt(linhaSelecionada, 0);

            Pacote pacote = buscarPacoteNaLista(nome);
            int resposta = JOptionPane.showConfirmDialog(rootPane,
                    "Tem certeza que deseja excluir o pacote " + pacote.getNomePacote() + "? "
                    + "Essa ação não poderá ser revertida.",
                    "Selecione uma Opção",
                    JOptionPane.YES_NO_OPTION);

            if (resposta != 1 & resposta != 2 & resposta != -1) {
                try {
                    controllerPacotes.deletarCadastroPacote(pacote.getIdPacote());
                    JOptionPane.showMessageDialog(this, "Pacote excluido com sucesso!");
                    popularTabelaPacote();
                } catch (SQLException e) {
                    Logger.getLogger(MenuPacote.class.getName()).log(Level.SEVERE, null, e);
                    JOptionPane.showMessageDialog(this, "Ocorreu um erro ao excluir o pacote."
                            + "Tente novamente!");
                } catch (ParseException ex) {
                    Logger.getLogger(MenuPacote.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(this, "Ocorreu um erro ao converter a data do cadastro."
                            + "Tente novamente!");
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Nenhum pacote foi selecionado!");
        }
    }//GEN-LAST:event_excluirPacoteActionPerformed

    private void popularTabelaPacote() throws ParseException {
        dtm = (DefaultTableModel) tabelaPacotes.getModel();
        dtm.setNumRows(0);
        float valorComDesconto = 0;
        listaDePacotes = controllerPacotes.getListaDePacotes();
        System.out.println(listaDePacotes.size());
        for (Pacote pacote : listaDePacotes) {
            for (int i = 0; i < pacote.getListaDeModalidades().size(); i++) {
                valorComDesconto += pacote.getListaDeModalidades().get(i).getValorModalidade();
            }
            valorComDesconto = valorComDesconto * pacote.getDuracao();
            valorComDesconto = valorComDesconto - pacote.getValorDesconto();
            dtm.addRow(new Object[]{
                pacote.getNomePacote(),
                valorComDesconto,
                pacote.getDuracao(),});
            valorComDesconto = 0;
        }
    }


    private void cadastrarPacoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarPacoteActionPerformed
        CadastroEdicaoPacote cadastroEdicaoPacote = new CadastroEdicaoPacote();
        cadastroEdicaoPacote.setVisible(true);
        dispose();
    }//GEN-LAST:event_cadastrarPacoteActionPerformed

    private void jButtonInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInicialActionPerformed
        MenuInicial menuInicial = new MenuInicial();
        menuInicial.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonInicialActionPerformed

    private void jButtonGerenciarModalidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGerenciarModalidadesActionPerformed
        MenuModalidade menuModalidade = new MenuModalidade();
        menuModalidade.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonGerenciarModalidadesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPacote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPacote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPacote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPacote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MenuPacote().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrarPacote;
    private javax.swing.JButton editarPacote;
    private javax.swing.JButton excluirPacote;
    private javax.swing.JButton gerenciarAlunosButton;
    private javax.swing.JButton jButtonGerenciarCustos;
    private javax.swing.JButton jButtonGerenciarModalidades;
    private javax.swing.JButton jButtonGerenciarPacotes;
    private javax.swing.JButton jButtonInicial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField pacoteFiltro;
    private javax.swing.JTable tabelaPacotes;
    // End of variables declaration//GEN-END:variables

    private void filtrar(String nome) {
        try {
            TableRowSorter<DefaultTableModel> resultadoFiltro = new TableRowSorter<>(dtm);
            tabelaPacotes.setRowSorter(resultadoFiltro);
            resultadoFiltro.setRowFilter(RowFilter.regexFilter(nome));
        } catch (Exception e) {
            System.out.println("Caractere não aceito.");
        }
    }
}
